volumes:
  radscheduler_local_postgres_data: {}
  radscheduler_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: radscheduler_local_django
    container_name: radscheduler_local_django
    depends_on:
      - postgres
      - mailpit
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: radscheduler_production_postgres
    container_name: radscheduler_local_postgres
    volumes:
      - radscheduler_local_postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  mailpit:
    image: axllent/mailpit:v1.8
    container_name: radscheduler_local_mailpit
    ports:
      - "8025:8025"

  firefox:
    image: selenium/standalone-firefox:4.14.1-20231025
    shm_size: 2gb
    ports:
      - "4444:4444"
      - "7900:7900"
    environment:
      - SE_NODE_SESSION_TIMEOUT=1800