# Generated by Django 4.2.6 on 2023-10-17 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveForm",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("employee_number", models.CharField(blank=True, max_length=20, null=True)),
                ("contact_number", models.CharField(blank=True, max_length=20, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_edited", models.DateTimeField(auto_now=True)),
                ("approved", models.BooleanField(default=False)),
                ("registrar", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.registrar")),
            ],
        ),
        migrations.CreateModel(
            name="LeaveRow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("return_date", models.DateField()),
                ("total_hours", models.IntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            (1, "Annual"),
                            (2, "Education"),
                            (3, "Conference"),
                            (4, "Bereavement"),
                            (5, "Lieu day"),
                            (6, "Parental"),
                            (7, "Sick"),
                        ],
                        max_length=10,
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="leave_application.leaveform",
                    ),
                ),
            ],
        ),
    ]
