# Generated by Django 4.2.6 on 2023-10-17 10:39

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Leave",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(verbose_name="date of leave")),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (1, "Annual"),
                            (2, "Education"),
                            (3, "Conference"),
                            (4, "Bereavement"),
                            (5, "Lieu day"),
                            (6, "Parental"),
                            (7, "Sick"),
                        ]
                    ),
                ),
                (
                    "portion",
                    models.CharField(
                        choices=[("ALL", "All day"), ("AM", "AM"), ("PM", "PM")],
                        default="ALL",
                        max_length=5,
                        verbose_name="portion of day",
                    ),
                ),
                ("approved", models.BooleanField(default=False)),
                ("cancelled", models.BooleanField(default=False)),
                ("comment", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_edited", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Registrar",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("employee_number", models.CharField(blank=True, max_length=20, null=True)),
                ("senior", models.BooleanField(default=False)),
                (
                    "start",
                    models.DateField(
                        blank=True, help_text="Date started training", null=True, verbose_name="start date"
                    ),
                ),
                (
                    "finish",
                    models.DateField(
                        blank=True, help_text="Date finished training", null=True, verbose_name="finish date"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_edited", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start", models.DateField(verbose_name="start date")),
                ("end", models.DateField(verbose_name="end date")),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (1, "Pre-oncall"),
                            (2, "Reliever"),
                            (3, "Part time non-working day"),
                            (4, "Pre-exam"),
                            (5, "Buddy required"),
                            (6, "Not available"),
                        ]
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_edited", models.DateTimeField(auto_now=True)),
                (
                    "weekdays",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(
                            choices=[
                                (1, "MON"),
                                (2, "TUE"),
                                (3, "WED"),
                                (4, "THUR"),
                                (5, "FRI"),
                                (6, "SAT"),
                                (7, "SUN"),
                            ]
                        ),
                        default=list,
                        size=7,
                    ),
                ),
                (
                    "shift_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[("LONG", "Long day"), ("NIGHT", "Night"), ("RDO", "RDO"), ("SLEEP", "Sleep")],
                            max_length=10,
                        ),
                        default=list,
                        size=None,
                    ),
                ),
                ("registrar", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.registrar")),
            ],
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(verbose_name="shift date")),
                (
                    "type",
                    models.CharField(
                        choices=[("LONG", "Long day"), ("NIGHT", "Night"), ("RDO", "RDO"), ("SLEEP", "Sleep")],
                        max_length=10,
                        verbose_name="shift type",
                    ),
                ),
                ("stat_day", models.BooleanField(default=False)),
                ("extra_duty", models.BooleanField(default=False)),
                ("fatigue_override", models.FloatField(default=0.0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_edited", models.DateTimeField(auto_now=True)),
                (
                    "registrar",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.registrar"
                    ),
                ),
            ],
        ),
    ]
