# Generated by Django 4.2.6 on 2023-11-18 01:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leave",
            name="type",
            field=models.CharField(
                choices=[
                    ("ANNUAL", "Annual"),
                    ("BE", "Bereavement"),
                    ("LIEU", "Lieu day"),
                    ("SICK", "Sick"),
                    ("PAR", "Parental"),
                    ("EDU", "Education"),
                    ("CONF", "Conference"),
                ],
                max_length=10,
            ),
        ),
    ]
