# Generated by Django 4.2.6 on 2023-10-17 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("leave_application", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="form",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="leave_application.leaveform"
            ),
        ),
        migrations.AddField(
            model_name="leave",
            name="registrar",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.registrar"),
        ),
        migrations.AlterUniqueTogether(
            name="shift",
            unique_together={("date", "type", "registrar", "extra_duty")},
        ),
        migrations.AlterUniqueTogether(
            name="leave",
            unique_together={("date", "type", "registrar")},
        ),
    ]
