# Generated by Django 4.2.2 on 2023-10-01 05:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="status",
            name="shift_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("LONG", "Long day"),
                        ("NIGHT", "Night"),
                        ("RDO", "RDO"),
                        ("SLP", "Sleep day"),
                    ],
                    max_length=10,
                ),
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="status",
            name="weekdays",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(
                    choices=[
                        (1, "MON"),
                        (2, "TUE"),
                        (3, "WED"),
                        (4, "THUR"),
                        (5, "FRI"),
                        (6, "SAT"),
                        (7, "SUN"),
                    ]
                ),
                default=list,
                size=7,
            ),
        ),
    ]
