# Generated by Django 4.2.6 on 2023-11-21 07:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_leave_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="shift_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[("LONG", "Long day"), ("NIGHT", "Night"), ("RDO", "RDO"), ("SLEEP", "Sleep")],
                    max_length=10,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="weekdays",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(
                    choices=[(0, "MON"), (1, "TUE"), (2, "WED"), (3, "THUR"), (4, "FRI"), (5, "SAT"), (6, "SUN")]
                ),
                blank=True,
                default=list,
                size=7,
            ),
        ),
    ]
