# Generated by Django 4.2.2 on 2023-10-06 23:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_status_shift_types_status_weekdays"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="leave",
            unique_together={("date", "type", "registrar")},
        ),
        migrations.AlterUniqueTogether(
            name="shift",
            unique_together={("date", "type", "registrar")},
        ),
    ]
