# Generated by Django 4.2.6 on 2023-11-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_status_shift_types_alter_status_weekdays"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="no_abutting_weekend",
            field=models.BooleanField(default=True),
        ),
    ]
