# Generated by Django 4.2.6 on 2023-12-26 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_leave_no_abutting_weekend"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="shift",
            unique_together={("date", "registrar", "extra_duty")},
        ),
        migrations.CreateModel(
            name="ShiftInterest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("comment", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_edited", models.DateTimeField(auto_now=True)),
                ("registrar", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.registrar")),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="interests", to="core.shift"
                    ),
                ),
            ],
        ),
    ]
