# Generated by Django 4.2.6 on 2023-12-26 09:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_shift_unique_together_shiftinterest"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shiftinterest",
            options={"verbose_name_plural": "shift interests"},
        ),
        migrations.AlterUniqueTogether(
            name="shiftinterest",
            unique_together={("shift", "registrar")},
        ),
    ]
