# Generated by Django 4.2.6 on 2025-01-31 06:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_shiftinterest_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="shift",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="shift",
            name="type",
            field=models.CharField(
                choices=[
                    ("LONG", "Long day"),
                    ("SWING", "Swing shift"),
                    ("HELP", "Help desk"),
                    ("RDO", "RDO"),
                    ("NIGHT", "Night"),
                    ("SLEEP", "Sleep"),
                ],
                max_length=10,
                verbose_name="shift type",
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="shift_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("LONG", "Long day"),
                        ("SWING", "Swing shift"),
                        ("HELP", "Help desk"),
                        ("RDO", "RDO"),
                        ("NIGHT", "Night"),
                        ("SLEEP", "Sleep"),
                    ],
                    max_length=10,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
