# Generated by Django 5.2.9 on 2025-12-28 02:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_shift_unique_together_alter_shift_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='type',
            field=models.CharField(choices=[('ANNUAL', 'Annual'), ('EDU', 'Education'), ('CONF', 'Conference'), ('LIEU', 'Lieu day'), ('SICK', 'Sick'), ('PAR', 'Parental'), ('BE', 'Bereavement')], max_length=10),
        ),
        migrations.AlterField(
            model_name='shift',
            name='type',
            field=models.CharField(choices=[('SWING', 'Swing day'), ('HELP', 'Help desk'), ('LONG', 'Long day'), ('RDO', 'RDO'), ('NIGHT', 'Night'), ('SLEEP', 'Sleep')], max_length=10, verbose_name='shift type'),
        ),
        migrations.AlterField(
            model_name='status',
            name='shift_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('SWING', 'Swing day'), ('HELP', 'Help desk'), ('LONG', 'Long day'), ('RDO', 'RDO'), ('NIGHT', 'Night'), ('SLEEP', 'Sleep')], max_length=10), blank=True, default=list, size=None),
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_start_date', models.DateField(help_text='Shifts and leaves before this date will not be displayed', verbose_name='publish start date')),
                ('publish_end_date', models.DateField(help_text='Shifts and leaves after this date will not be displayed', verbose_name='publish end date')),
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'settings',
                'constraints': [models.CheckConstraint(condition=models.Q(('publish_start_date__lte', models.F('publish_end_date'))), name='valid_date_range')],
            },
        ),
    ]
