# Generated by Django 5.2.9 on 2025-12-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_leave_type_alter_shift_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='date',
            field=models.DateField(db_index=True, verbose_name='date of leave'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='date',
            field=models.DateField(db_index=True, verbose_name='shift date'),
        ),
    ]
