# Generated by Django 5.2.9 on 2025-12-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_date_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['registrar'], name='core_leave_registr_440c22_idx'),
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['cancelled'], name='core_leave_cancell_943dfb_idx'),
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['registrar', 'date'], name='core_leave_registr_5a07b6_idx'),
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['cancelled', 'reg_approved', 'dot_approved'], name='core_leave_cancell_a9e654_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['registrar'], name='core_shift_registr_1f9c84_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['type'], name='core_shift_type_fa042c_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['extra_duty'], name='core_shift_extra_d_02a0a1_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['date', 'type'], name='core_shift_date_890e90_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['registrar', 'date'], name='core_shift_registr_66b3c1_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftinterest',
            index=models.Index(fields=['shift'], name='core_shifti_shift_i_3c6658_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftinterest',
            index=models.Index(fields=['registrar'], name='core_shifti_registr_1eb2f8_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftinterest',
            index=models.Index(fields=['shift', 'registrar'], name='core_shifti_shift_i_b36418_idx'),
        ),
        migrations.AddIndex(
            model_name='status',
            index=models.Index(fields=['registrar'], name='core_status_registr_c333a0_idx'),
        ),
        migrations.AddIndex(
            model_name='status',
            index=models.Index(fields=['registrar', 'start', 'end'], name='core_status_registr_c6cd49_idx'),
        ),
        migrations.AddIndex(
            model_name='status',
            index=models.Index(fields=['type'], name='core_status_type_629bb7_idx'),
        ),
    ]
